import { Inter } from "next/font/google";
import "./globals.css";
import GameProvider from "@/contexts/GameContext";
import { TimerProvider } from "@/contexts/TimerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GameProvider>
          <TimerProvider>{children}</TimerProvider>
        </GameProvider>
      </body>
    </html>
  );
}
