import { Inter } from "next/font/google";
import "./globals.css";
import GameProvider from "@/contexts/GameContext";
import { TimerProvider } from "@/contexts/TimerContext";
import ScoreProvider from "@/contexts/ScoreContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TimerProvider>
          <ScoreProvider>
            <GameProvider>{children}</GameProvider>
          </ScoreProvider>
        </TimerProvider>
      </body>
    </html>
  );
}
