import { Inter, Open_Sans, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import QuizProvider from "@/contexts/QuizContext";
import { TimerProvider } from "@/contexts/TimerContext";
import ScoreProvider from "@/contexts/ScoreContext";
import Navbar from "@/components/Navbar";

const font = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <TimerProvider>
          <ScoreProvider>
            <QuizProvider>
              <Navbar />
              <div className=" w-11/12 max-w-screen-xl md:px-0 mx-auto">
                {children}
              </div>
            </QuizProvider>
          </ScoreProvider>
        </TimerProvider>
      </body>
    </html>
  );
}
