export const questions = [
  {
    _id: "66870d84ba044061b507571c",
    id: "4101",
    exam_id: "1003",
    name: "………………..is defined as the degree of pathogenicity of infectious agent.",
    opt_a: "Communicable",
    opt_b: "Virulence",
    opt_c: "Infection",
    opt_d: "Incubation period",
    opt_correct: "B",
    __v: 0,
  },
  {
    _id: "66870c50ba044061b50719f6",
    id: "2155",
    exam_id: "1001",
    name: "कार्यमूलक अनुसन्धानको कार्य चरणअन्तर्गत कुन कुन पर्दछन् ?",
    opt_a: "समस्या पहिचान, योजना, कार्य, प्रतिविम्बन",
    opt_b: "समस्या विश्लेषण, योजना, कार्यान्वयन, प्रयोग",
    opt_c: "योजना, कार्य, अवलोकन, प्रतिविम्बन",
    opt_d: "कार्य, योजना, प्रतिविम्बन, अवलोकन",
    opt_correct: "C",
    __v: 0,
  },
  {
    _id: "66870d84ba044061b5074b45",
    id: "1070",
    exam_id: "1003",
    name: "Sustainable development goals (SGDs) sf] cjwL slt /fvLPsf] 5 <",
    opt_a: "2015 to 2020 AD",
    opt_b: "2015 to 2025 AD",
    opt_c: "2016 to 2030 AD",
    opt_d: "1997 to 2017 AD",
    opt_correct: "C",
    __v: 0,
  },
  {
    _id: "66870ed7ba044061b507ac8e",
    id: "183",
    exam_id: "1010",
    name: "139. Which Of The Following Does Not Work On The Existence Of Atmospheric Pressure?",
    opt_a: "a. Rise of iodine solution in the glass tube of dropper",
    opt_b: "b. Rise of cold drink in a long plastic straw",
    opt_c: "c. Sticking of suction hook on the wall of a room",
    opt_d: "d. Rise of mercury in glass tube of thermometer",
    opt_correct: "C",
    __v: 0,
  },
  {
    _id: "66870e17ba044061b50784c8",
    id: "776",
    exam_id: "1005",
    name: "Canine distemper is caused by",
    opt_a: "Orthomyxovirus",
    opt_b: "Paramyxovirus",
    opt_c: "Rhabdovirus",
    opt_d: "None of the above",
    opt_correct: "A",
    __v: 0,
  },
  {
    _id: "66870ea4ba044061b5078a6a",
    id: "249",
    exam_id: "1007",
    name: "सुरक्षा परिषद्मा सर्वप्रथम भिये प्रयोग गर्ने राष्ट्र कुन हो ?",
    opt_a: "बेलायत",
    opt_b: "रसिया",
    opt_c: "फ्रान्स",
    opt_d: "जर्मनी",
    opt_correct: "A",
    __v: 0,
  },
  {
    _id: "66870d85ba044061b5076e64",
    id: "10061",
    exam_id: "1003",
    name: "Health is a state of complete physical, mental and social well-being and not merely the absence of disease or deformity. this was given by:",
    opt_a: "Nepal league for nursing",
    opt_b: "World Health Organization",
    opt_c: "National Institute of Health",
    opt_d: "Nepal government",
    opt_correct: "B",
    __v: 0,
  },
  {
    _id: "66870eb6ba044061b507978d",
    id: "2876",
    exam_id: "1008",
    name: "नेपालमा iucn ले वर्गीकृत गरेका संरक्षित क्षेत्रहरु कति वटा छन?",
    opt_a: "3",
    opt_b: "11",
    opt_c: "12",
    opt_d: "13",
    opt_correct: "A",
    __v: 0,
  },
  {
    _id: "66870c51ba044061b5073dc4",
    id: "11321",
    exam_id: "1001",
    name: "पाठ्यक्रमको आधुनिक अवधारणाले कुन पक्षलाई जनाउँछ ?",
    opt_a: "सिकाइ प्रक्रिया",
    opt_b: "विषयवस्तुहरु",
    opt_c: "सिकाइको माध्ययम",
    opt_d: "सिकाइको योजना",
    opt_correct: "D",
    __v: 0,
  },
  {
    _id: "66870c51ba044061b5072d9f",
    id: "7188",
    exam_id: "1001",
    name: "Computer मा Output अन्तर्गत कुन पर्दछ?",
    opt_a: "मनिटर",
    opt_b: "स्पिकर",
    opt_c: "प्रिन्टर",
    opt_d: "माथिका सबै",
    opt_correct: "D",
    __v: 0,
  },
  {
    _id: "66870c51ba044061b507422f",
    id: "12452",
    exam_id: "1001",
    name: "स्थानीय निकायले निरक्षर नागरिक, अपाङ्ग बालबालिका, बीचैमा पढाइ छाडेका, अध्ययनरत बालबालिको लगत कहिले तयार गरिसक्नुपर्दछ ?",
    opt_a: "शैक्षिक सत्र समाप्त भएको १५ दिनभित्र",
    opt_b: "शैक्षिक सत्र समाप्त भएको एक महिना भित्र",
    opt_c: "शैक्षिक सत्र समाप्त भएको ४५ दिनभित्र",
    opt_d: "शैक्षिक सत्र समाप्त भएको ६० दिनभित्र",
    opt_correct: "B",
    __v: 0,
  },
  {
    _id: "66870c51ba044061b50721ec",
    id: "4193",
    exam_id: "1001",
    name: "तलका भनाइहरू ठीक बेठीक के हुन् ? १. पृथ्वी सूर्यको सबैभन्दा नजिक भएको अवस्थालाई Perihelion भनिन्छ , जो सामान्यतया जनवरी ३ मा पर्छ। २. पृथ्वी सूर्यबाट सबैभन्दा टाढा भएको अवस्थालाई Aphelion भनिन्छ , जो सामान्यतया जुलाई ४ मा पर्छ ।",
    opt_a: "१ ठीक २ बेठीक",
    opt_b: "१ बेठीक २ ठीक",
    opt_c: "दुवै ठीक",
    opt_d: "दुवै बेठिक",
    opt_correct: "C",
    __v: 0,
  },
  {
    _id: "66870eb6ba044061b50793f0",
    id: "1951",
    exam_id: "1008",
    name: "हिउँ चितुवा मार्न चोरी शिकारीहरूले के विधि अपनाउछन्?",
    opt_a: "पासो थाप्छन्",
    opt_b: "हिउँ चितुवाले मारेको जनावरमा विष हाली दिन्छन",
    opt_c: "क र ख दुवै",
    opt_d: "खोर थाप्छन्",
    opt_correct: "C",
    __v: 0,
  },
  {
    _id: "66870eb6ba044061b507971c",
    id: "2763",
    exam_id: "1008",
    name: "रुखको गोलाई मापन गर्दा 1.3 मिटर( छातीको उचाई) मा गाठों भएको कसरी मापन गरिन्छ ?",
    opt_a: "त्यसमा नप्ने",
    opt_b: "तलमाथि नापेर औसत निकाल्ने",
    opt_c: "अन्दाज गर्ने",
    opt_d: "ननाप्ने छोडिदिने",
    opt_correct: "B",
    __v: 0,
  },
  {
    _id: "66870d84ba044061b5075d7d",
    id: "5734",
    exam_id: "1003",
    name: "Which of the following cholesterol is bad for human Body ?",
    opt_a: "LDL",
    opt_b: "HDL",
    opt_c: "DDL",
    opt_d: "None",
    opt_correct: "A",
    __v: 0,
  },
  {
    _id: "66870ed7ba044061b507adcf",
    id: "504",
    exam_id: "1010",
    name: "निम्नमध्ये कुन योजना पाठ्यक्रम विकास केन्द्रले तयार गर्दछ ?",
    opt_a: "कार्यपात्रो",
    opt_b: "कार्ययोजना",
    opt_c: "पाठयोजना",
    opt_d: "एकाइ योजना",
    opt_correct: "D",
    __v: 0,
  },
  {
    _id: "66870d84ba044061b5074d29",
    id: "1554",
    exam_id: "1003",
    name: "दिसा जाँच गर्नु नपर्ने अवस्था कुन हो ?",
    opt_a: "Ulcer",
    opt_b: "Cholera",
    opt_c: "Nephritis",
    opt_d: "Typhoid",
    opt_correct: "C",
    __v: 0,
  },
  {
    _id: "66870d84ba044061b5074e84",
    id: "1901",
    exam_id: "1003",
    name: "Hematemesis तलका मध्ये कुन रोगमा 40. Pellagra रोग Vitamin 'B' को कमीले लाग्छ देखिन्छ ?",
    opt_a: "Bronchitis",
    opt_b: "TB",
    opt_c: "Peptic ulcer",
    opt_d: "माथिका सबै",
    opt_correct: "C",
    __v: 0,
  },
  {
    _id: "66870c51ba044061b5073990",
    id: "10245",
    exam_id: "1001",
    name: "३३. राष्ट्रिय पाठ्यव्र m म प्रारूप , २०७६ माध्यमिक शिक्षाका प्रकार के के हुन् ?",
    opt_a: "साधारण",
    opt_b: "परम्परागत",
    opt_c: "प्राविधिक र व्यावसायिक",
    opt_d: "माथिका सबै",
    opt_correct: "D",
    __v: 0,
  },
  {
    _id: "66870d84ba044061b5074bcc",
    id: "1205",
    exam_id: "1003",
    name: "Sleep inducing drug is:",
    opt_a: "Hypnotics",
    opt_b: "Tranquilize",
    opt_c: "Sedatives",
    opt_d: "Emetics",
    opt_correct: "A",
    __v: 0,
  },
];
